---
# tasks file for ha_haproxy

- name: Assert target os_family is supported
  ansible.builtin.assert:
    that: ansible_os_family in ha_haproxy_supported_os_families
    fail_msg: "Unsupported os_family '{{ ansible_os_family }}'"
    quiet: true
  tags:
    - always

- name: Install required packages
  ansible.builtin.include_tasks: "pkg-install-{{ ansible_os_family }}.yml"

- name: Configure firewall
  ansible.builtin.include_tasks: "firewall-{{ ansible_os_family }}.yml"

- name: Configure SELinux
  ansible.builtin.include_tasks: selinux.yml
  when: ha_haproxy_selinux_enabled | bool

- name: Configure keepalived
  ansible.builtin.include_tasks: keepalived.yml
  tags: keepalived_reconfig

- name: Configure haproxy
  ansible.builtin.include_tasks: haproxy.yml
  tags: haproxy_reconfig
