---
# handlers file for ha_haproxy
- name: Restart rsyslog
  become: true
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted

- name: Restart keepalived
  become: true
  ansible.builtin.systemd:
    name: keepalived
    state: restarted

- name: Restart haproxy
  become: true
  ansible.builtin.systemd:
    name: haproxy
    state: restarted
